import type { JobMatch } from "./storage";

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

export const mockJobs: JobMatch[] = [
  {
    id: "1",
    title: "Machine Learning Engineer Intern",
    company: "Anthropic",
    location: "Remote",
    type: "Internship",
    remote: true,
    score: 96,
    reason: "Matches your PyTorch + LLM evaluation background",
    query: "ML Intern Remote 2025",
    postedAt: hoursAgo(3),
    url: "#",
  },
  {
    id: "2",
    title: "Applied AI Engineer",
    company: "Perplexity",
    location: "Bangalore, IN",
    type: "Full-time",
    remote: false,
    score: 91,
    reason: "Strong fit: RAG, vector DBs, production ML",
    query: "Applied AI India",
    postedAt: hoursAgo(8),
    url: "#",
  },
  {
    id: "3",
    title: "Software Engineer Intern — Infra",
    company: "Razorpay",
    location: "Bangalore, IN",
    type: "Internship",
    remote: false,
    score: 88,
    reason: "Go + distributed systems experience aligns",
    query: "SWE Intern India",
    postedAt: hoursAgo(14),
    url: "#",
  },
  {
    id: "4",
    title: "Data Scientist (NLP)",
    company: "Sarvam AI",
    location: "Bangalore, IN",
    type: "Full-time",
    remote: false,
    score: 87,
    reason: "Indic NLP + transformer fine-tuning match",
    query: "NLP Engineer India",
    postedAt: hoursAgo(20),
    url: "#",
  },
  {
    id: "5",
    title: "ML Research Intern",
    company: "Hugging Face",
    location: "Remote",
    type: "Internship",
    remote: true,
    score: 84,
    reason: "Open-source ML contributions match profile",
    query: "Research Intern Remote",
    postedAt: hoursAgo(28),
    url: "#",
  },
  {
    id: "6",
    title: "Backend Engineer — Platform",
    company: "Zerodha",
    location: "Bangalore, IN",
    type: "Full-time",
    remote: false,
    score: 79,
    reason: "Go + PostgreSQL + high-throughput systems",
    query: "Backend India 2025",
    postedAt: hoursAgo(36),
    url: "#",
  },
  {
    id: "7",
    title: "MLOps Intern",
    company: "Replicate",
    location: "Remote",
    type: "Internship",
    remote: true,
    score: 76,
    reason: "MLOps + Kubernetes + model serving overlap",
    query: "MLOps Intern Remote",
    postedAt: hoursAgo(45),
    url: "#",
  },
  {
    id: "8",
    title: "Data Engineering Intern",
    company: "Swiggy",
    location: "Bangalore, IN",
    type: "Internship",
    remote: false,
    score: 74,
    reason: "Spark + Airflow experience relevant",
    query: "Data Eng Intern India",
    postedAt: hoursAgo(52),
    url: "#",
  },
  {
    id: "9",
    title: "Full-Stack Engineer (Early Career)",
    company: "Linear",
    location: "Remote",
    type: "Full-time",
    remote: true,
    score: 72,
    reason: "TypeScript + React + product engineering fit",
    query: "Full-stack Remote Entry",
    postedAt: hoursAgo(60),
    url: "#",
  },
  {
    id: "10",
    title: "AI Product Engineer",
    company: "Cursor",
    location: "Remote",
    type: "Full-time",
    remote: true,
    score: 69,
    reason: "LLM tooling + IDE integrations experience",
    query: "AI Product Engineer",
    postedAt: hoursAgo(70),
    url: "#",
  },
  {
    id: "11",
    title: "Computer Vision Intern",
    company: "Niramai",
    location: "Bangalore, IN",
    type: "Internship",
    remote: false,
    score: 64,
    reason: "Medical imaging + CNN expertise",
    query: "CV Intern India",
    postedAt: hoursAgo(80),
    url: "#",
  },
  {
    id: "12",
    title: "Software Engineer I",
    company: "Atlassian",
    location: "Bangalore, IN",
    type: "Full-time",
    remote: false,
    score: 61,
    reason: "Java + AWS + agile team experience",
    query: "SWE Entry India",
    postedAt: hoursAgo(96),
    url: "#",
  },
  {
    id: "13",
    title: "Frontend Engineer Intern",
    company: "Vercel",
    location: "Remote",
    type: "Internship",
    remote: true,
    score: 58,
    reason: "Next.js + React performance work",
    query: "Frontend Intern Remote",
    postedAt: hoursAgo(110),
    url: "#",
  },
  {
    id: "14",
    title: "Quantitative Developer Intern",
    company: "WorldQuant",
    location: "Mumbai, IN",
    type: "Internship",
    remote: false,
    score: 54,
    reason: "Python + statistical modelling",
    query: "Quant Intern India",
    postedAt: hoursAgo(130),
    url: "#",
  },
  {
    id: "15",
    title: "Site Reliability Engineer",
    company: "Cloudflare",
    location: "Remote",
    type: "Full-time",
    remote: true,
    score: 48,
    reason: "Infra automation + observability",
    query: "SRE Remote",
    postedAt: hoursAgo(150),
    url: "#",
  },
];
